### ISSUE TITLE
[BE] 회원가입 기능 구현 - 3h

### ISSUE THREAD

**Issue by earthkid0** [codestates-seb/seb44_main_027#15]
**만들고자 하는 기능이 무엇인가요?**
사용자가 사용할 수 있는 회원가입 기능을 구현한다.

**해당 기능을 구현하기 위해 할 일이 무엇인가요?**

- [x] 회원가입 기능 구현
- [x] 회원가입 유효성 검사
- [x] 회원탈퇴 기능 구현
- [x] 개인정보 수정 기능 구현

**예상 작업 시간**
3h

**Comment by inha1234** [comment]
지금 단계에서는 토큰을 쓰지 않으니깐
이메일 말고는 클라이언트에서의 요청을 구분할 방법이 없어서
저렇게 쓰는데 토큰이 구현되면
해당부분 적용해야함

- [x] 시큐리티 구현되면 적용하고 수정할 부분 수정하기(전체적으로)
- [x] 유저 활동여부 확인 로직(현재는 email로 찾는부분과 memberId로 찾는 부분 두 부분으로 나눠져 있어서 해당 로직이 2개 있는데) 리팩토링하기(시큐리티 이후?)
- [x] 닉네임 중복확인 구현해야함.(닉네임과 이메일이 두가지 모두 중복일 경우도 알려줘야하는 것도 구현해야함)
